
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Lvp-YWB6ifqaOlm_mayHSwB71pHiP3A',
    appId: '1:676712352074:web:be8b8e3bf9c922f5ac99b3',
    messagingSenderId: '676712352074',
    projectId: 'instamilligram-aa2e7',
    authDomain: 'instamilligram-aa2e7.firebaseapp.com',
    storageBucket: 'instamilligram-aa2e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp3wu6pFw99kSvyBo3mllu-7QA9QjuDQg',
    appId: '1:676712352074:android:7f51fb8abde0b309ac99b3',
    messagingSenderId: '676712352074',
    projectId: 'instamilligram-aa2e7',
    storageBucket: 'instamilligram-aa2e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39CaSHWBBgPt_Txe3SbwWvdIIGqH9yy0',
    appId: '1:676712352074:ios:055565ce3d3546d7ac99b3',
    messagingSenderId: '676712352074',
    projectId: 'instamilligram-aa2e7',
    storageBucket: 'instamilligram-aa2e7.appspot.com',
    iosBundleId: 'com.example.instamilligram',
  );
}